version: '2.1'
services:
  localstack:
    image: localstack/localstack:0.14.2
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=sqs,sns,s3,cloudwatch
      - DEBUG=1
  ready:
    image: dadarek/wait-for-dependencies
    command: localstack:4566
    depends_on:
      - localstack
